// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Famille de formats, pour regrouper les onglets.
 */
export type Category = "bytes" | "web" | "text" | "cipher";
