// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { Span } from "./Span";

/**
 * Erreur de conversion : un code stable, un message en français et, quand elle est
 * connue, la plage fautive dans le texte saisi.
 */
export type CodecError = { code: ErrorCode, message: string, span: Span | null, };
