// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { OptionSpec } from "./OptionSpec";

/**
 * Description d'un format pour l'interface et les recettes.
 */
export type CodecMeta = { 
/**
 * Identifiant stable : interface, recettes, ligne de commande.
 */
id: string, label: string, 
/**
 * Libellé court affiché dans l'onglet.
 */
icon: string, category: Category, 
/**
 * Autres noms acceptés par le registre.
 */
aliases: Array<string>, 
/**
 * Décoder l'encodage redonne le texte d'origine, s'il est bien formé.
 */
reversible: boolean, 
/**
 * L'encodage attend du texte UTF-8 ; sinon, il accepte des octets quelconques.
 */
encodes_text: boolean, options: Array<OptionSpec>, };
