// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Output } from "./Output";

export type ConvertResponse = { output: Output, input_chars: number, input_bytes: number, 
/**
 * Caractères du texte produit, ou nombre d'octets s'il ne s'agit pas de texte.
 */
output_chars: number, output_bytes: number, };
