// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Options } from "./Options";

/**
 * Demande de conversion envoyée par l'interface.
 */
export type ConvertRequest = { 
/**
 * Identifiant ou alias du format.
 */
codec: string, direction: Direction, input: string, options: Options, };
