// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nature d'une erreur. Stable : l'interface peut s'en servir pour traduire le message.
 */
export type ErrorCode = "invalid_character" | "invalid_length" | "invalid_padding" | "mixed_alphabets" | "invalid_number" | "unknown_symbol" | "unsupported_character" | "invalid_domain" | "invalid_punycode" | "invalid_data_uri" | "invalid_compressed_data" | "output_too_large" | "not_text" | "invalid_option" | "unknown_codec" | "invalid_recipe" | "irreversible_step" | "storage" | "internal";
