// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionValue } from "./OptionValue";

/**
 * Options d'un format, par identifiant. Une option absente prend sa valeur par défaut ;
 * une option que le format ne connaît pas est ignorée.
 */
export type Options = { [key in string]: OptionValue };
