// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionKind } from "./OptionKind";

/**
 * Option d'un format, décrite pour que l'interface puisse l'afficher.
 */
export type OptionSpec = { id: string, label: string, kind: OptionKind, };
