// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Valeur d'une option, telle qu'envoyée par l'interface.
 */
export type OptionValue = boolean | number | string;
