// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";

/**
 * Type d'une option, avec sa valeur par défaut.
 */
export type OptionKind = { "type": "bool", default: boolean, } | { "type": "choice", default: string, choices: Array<Choice>, } | { "type": "int", default: number, min: number, max: number, } | { "type": "text", default: string, secret: boolean, };
