// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résultat d'une conversion : du texte si les octets produits sont de l'UTF-8 valide,
 * sinon ces octets en hexadécimal.
 */
export type Output = { "kind": "text", text: string, } | { "kind": "bytes", hex: string, };
