// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { Span } from "./Span";

/**
 * Erreur d'une chaîne : la couche en cause et un message qui la nomme.
 */
export type PipelineError = { 
/**
 * Index de la couche, à partir de 0.
 */
step: number, code: ErrorCode, 
/**
 * Message précédé du numéro, du format et du sens de la couche.
 */
message: string, 
/**
 * Plage fautive dans le texte saisi, quand la couche en erreur est celle qui le lit.
 */
span: Span | null, };
