// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from "./Step";

/**
 * Chaîne à exécuter sur un texte saisi.
 */
export type PipelineRequest = { input: string, steps: Array<Step>, };
