// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Output } from "./Output";
import type { PipelineError } from "./PipelineError";
import type { StepReport } from "./StepReport";

/**
 * Résultat d'une chaîne, couche par couche.
 */
export type PipelineResponse = { 
/**
 * Un compte rendu par couche, dans l'ordre de la chaîne.
 */
steps: Array<StepReport>, 
/**
 * Sortie complète de la dernière couche ; absente si une couche a échoué.
 */
output: Output | null, input_chars: number, input_bytes: number, 
/**
 * Caractères du texte produit, ou nombre d'octets s'il ne s'agit pas de texte.
 */
output_chars: number, output_bytes: number, error: PipelineError | null, };
