// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recette prête à l'emploi.
 */
export type Preset = { id: string, name: string, description: string, 
/**
 * Forme courte de la recette.
 */
recipe: string, };
