// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Step } from "./Step";

/**
 * Recette sous sa forme JSON versionnée.
 */
export type Recipe = { 
/**
 * Version du format de recette.
 */
v: number, steps: Array<Step>, };
