// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Recipe } from "./Recipe";

/**
 * Recette enregistrée par l'utilisateur dans « Mes recettes ».
 */
export type SavedRecipe = { name: string, recipe: Recipe, };
