// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plage fautive dans le texte saisi, en caractères Unicode comptés à partir de 0,
 * fin exclue.
 */
export type Span = { start: number, end: number, };
