// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodecError } from "./CodecError";
import type { Output } from "./Output";
import type { StepStatus } from "./StepStatus";

/**
 * Compte rendu d'une couche.
 */
export type StepReport = { status: StepStatus, 
/**
 * Début de la sortie de la couche : [`PREVIEW_BYTES`] octets au plus.
 */
preview: Output | null, 
/**
 * La sortie est plus longue que son aperçu.
 */
truncated: boolean, 
/**
 * Taille de la sortie, en octets.
 */
bytes: number, 
/**
 * La sortie est du texte UTF-8 valide.
 */
is_text: boolean, 
/**
 * Durée de la couche, en microsecondes.
 */
micros: number, 
/**
 * Erreur du format ; sa plage porte sur l'entrée de la couche.
 */
error: CodecError | null, };
