// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Options } from "./Options";

/**
 * Une couche : un format, un sens et des options.
 */
export type Step = { 
/**
 * Identifiant ou alias du format.
 */
codec: string, direction: Direction, options: Options, 
/**
 * Une couche désactivée laisse passer les données sans les toucher.
 */
enabled: boolean, };
