// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * État d'une couche après l'exécution de la chaîne.
 */
export type StepStatus = "done" | "disabled" | "failed" | "skipped";
